// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerData.Database;

#nullable disable

namespace ServerData.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211230165714_UserBanRouteTrackDelay")]
    partial class UserBanRouteTrackDelay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1250_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RouteUser", b =>
                {
                    b.Property<int>("RoutesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RoutesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RouteUser");
                });

            modelBuilder.Entity("ServerData.Database.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("AActualDep")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("AActualDepTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("AAnnounced")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("AAnnouncedTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool?>("AApproval")
                        .HasColumnType("bit");

                    b.Property<string>("AComment")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ACommentTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<short?>("ADelay")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ADeparted")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ADepartedTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("AExceptions")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ANote")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ANoteTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ANumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("APMD")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("APMDTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ARouteId")
                        .HasColumnType("int");

                    b.Property<short?>("ASentMessages")
                        .HasColumnType("smallint");

                    b.Property<int?>("ATrackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ATrackTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("AType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Arrival")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DActualDep")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DActualDepTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DAnnounced")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DAnnouncedTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool?>("DApproval")
                        .HasColumnType("bit");

                    b.Property<string>("DComment")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("DCommentTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<short?>("DDelay")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DDeparted")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DDepartedTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DExceptions")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DNote")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("DNoteTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DPMD")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DPMDTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DRouteId")
                        .HasColumnType("int");

                    b.Property<short?>("DSentMessages")
                        .HasColumnType("smallint");

                    b.Property<int?>("DTrackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DTrackTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Departure")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("DepartureTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Left")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LeftTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<string>("Right")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RightTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("RowType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Sig1A")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig1ATime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig1D")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig1DTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig2A")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig2ATime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig2D")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig2DTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig3A")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig3ATime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig3D")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig3DTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig4A")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig4ATime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig4D")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Sig4DTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ARouteId");

                    b.HasIndex("ATrackId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DRouteId");

                    b.HasIndex("DTrackId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("TrainId");

                    b.ToTable("ArchiveRecords");
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Occupied")
                        .HasColumnType("bit");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ServerData.Database.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ServerData.Database.RouteTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<int>("MinimalDelay")
                        .HasColumnType("int");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Secured")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("RouteTracks");
                });

            modelBuilder.Entity("ServerData.Database.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ServerData.Database.Signaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Signallers");
                });

            modelBuilder.Entity("ServerData.Database.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Interlocking")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PrimaryId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryId")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.HasIndex("SecondaryId")
                        .IsUnique();

                    b.ToTable("StationConnections");
                });

            modelBuilder.Entity("ServerData.Database.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Arrival")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Departure")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("FromId")
                        .HasColumnType("int");

                    b.Property<int>("StationTrackId")
                        .HasColumnType("int");

                    b.Property<int?>("ToId")
                        .HasColumnType("int");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromId")
                        .IsUnique()
                        .HasFilter("[FromId] IS NOT NULL");

                    b.HasIndex("StationTrackId")
                        .IsUnique();

                    b.HasIndex("ToId")
                        .IsUnique()
                        .HasFilter("[ToId] IS NOT NULL");

                    b.HasIndex("TrackId");

                    b.HasIndex("TrainId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("RouteId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("ServerData.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("TokenIssued")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RouteUser", b =>
                {
                    b.HasOne("ServerData.Database.Route", null)
                        .WithMany()
                        .HasForeignKey("RoutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerData.Database.Archive", b =>
                {
                    b.HasOne("ServerData.Database.RouteTrack", "ARoute")
                        .WithMany()
                        .HasForeignKey("ARouteId");

                    b.HasOne("ServerData.Database.Track", "ATrack")
                        .WithMany()
                        .HasForeignKey("ATrackId");

                    b.HasOne("ServerData.Database.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.RouteTrack", "DRoute")
                        .WithMany()
                        .HasForeignKey("DRouteId");

                    b.HasOne("ServerData.Database.Track", "DTrack")
                        .WithMany()
                        .HasForeignKey("DTrackId");

                    b.HasOne("ServerData.Database.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId");

                    b.Navigation("ARoute");

                    b.Navigation("ATrack");

                    b.Navigation("Client");

                    b.Navigation("DRoute");

                    b.Navigation("DTrack");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Clients")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ServerData.Database.RouteTrack", b =>
                {
                    b.HasOne("ServerData.Database.StationConnection", "Connection")
                        .WithMany("RouteTracks")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("ServerData.Database.Shift", b =>
                {
                    b.HasOne("ServerData.Database.Client", "Client")
                        .WithMany("Shifts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServerData.Database.Signaller", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ServerData.Database.Station", b =>
                {
                    b.HasOne("ServerData.Database.Client", "Client")
                        .WithMany("Stations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Primary")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.StationConnection", "PrimaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Connections")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Station", "Secondary")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.StationConnection", "SecondaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Primary");

                    b.Navigation("Route");

                    b.Navigation("Secondary");
                });

            modelBuilder.Entity("ServerData.Database.Stop", b =>
                {
                    b.HasOne("ServerData.Database.RouteTrack", "From")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "FromId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServerData.Database.Track", "StationTrack")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "StationTrackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServerData.Database.RouteTrack", "To")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "ToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServerData.Database.Track", null)
                        .WithMany("TrainStops")
                        .HasForeignKey("TrackId");

                    b.HasOne("ServerData.Database.Train", "Train")
                        .WithMany("Stops")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("StationTrack");

                    b.Navigation("To");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Trains")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("ServerData.Database.Route", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Connections");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.Navigation("RouteTracks");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.Navigation("TrainStops");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("ServerData.Database.User", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
