// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerData.Database;

#nullable disable

namespace ServerData.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220602111640_DefaultDirection")]
    partial class DefaultDirection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1250_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RouteUser", b =>
                {
                    b.Property<int>("RoutesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RoutesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RouteUser");
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ServerData.Database.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ServerData.Database.RouteTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Interlocking")
                        .HasColumnType("tinyint");

                    b.Property<int>("MinimumInterval")
                        .HasColumnType("int");

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("RouteTracks");
                });

            modelBuilder.Entity("ServerData.Database.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short?>("ADelay")
                        .HasColumnType("smallint");

                    b.Property<int?>("APMDId")
                        .HasColumnType("int");

                    b.Property<int?>("AcceptedAId")
                        .HasColumnType("int");

                    b.Property<int?>("AcceptedDId")
                        .HasColumnType("int");

                    b.Property<int?>("ActualDepAId")
                        .HasColumnType("int");

                    b.Property<int?>("ActualDepDId")
                        .HasColumnType("int");

                    b.Property<int?>("AnnouncedAId")
                        .HasColumnType("int");

                    b.Property<int?>("AnnouncedDId")
                        .HasColumnType("int");

                    b.Property<bool?>("ApprovalA")
                        .HasColumnType("bit");

                    b.Property<bool?>("ApprovalD")
                        .HasColumnType("bit");

                    b.Property<int?>("ArrivalId")
                        .HasColumnType("int");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentAId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentDId")
                        .HasColumnType("int");

                    b.Property<short?>("DDelay")
                        .HasColumnType("smallint");

                    b.Property<int?>("DPMDId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartedAId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartedDId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartureId")
                        .HasColumnType("int");

                    b.Property<string>("ExceptionsA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExceptionsD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<int?>("NoteAId")
                        .HasColumnType("int");

                    b.Property<int?>("NoteDId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberA")
                        .HasColumnType("int");

                    b.Property<int?>("NumberD")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<string>("RouteA")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RouteD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RowChar")
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("RowComplete")
                        .HasColumnType("bit");

                    b.Property<byte>("RowType")
                        .HasColumnType("tinyint");

                    b.Property<short?>("SentMessagesA")
                        .HasColumnType("smallint");

                    b.Property<short?>("SentMessagesD")
                        .HasColumnType("smallint");

                    b.Property<int?>("Sig1AId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig1DId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig2AId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig2DId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig3AId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig3DId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig4AId")
                        .HasColumnType("int");

                    b.Property<int?>("Sig4DId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("TrackAId")
                        .HasColumnType("int");

                    b.Property<int?>("TrackDId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainId")
                        .HasColumnType("int");

                    b.Property<byte?>("TypeA")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("TypeD")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("APMDId");

                    b.HasIndex("AcceptedAId");

                    b.HasIndex("AcceptedDId");

                    b.HasIndex("ActualDepAId");

                    b.HasIndex("ActualDepDId");

                    b.HasIndex("AnnouncedAId");

                    b.HasIndex("AnnouncedDId");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("CommentAId");

                    b.HasIndex("CommentDId");

                    b.HasIndex("DPMDId");

                    b.HasIndex("DepartedAId");

                    b.HasIndex("DepartedDId");

                    b.HasIndex("DepartureId");

                    b.HasIndex("MessageId");

                    b.HasIndex("NoteAId");

                    b.HasIndex("NoteDId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("Sig1AId");

                    b.HasIndex("Sig1DId");

                    b.HasIndex("Sig2AId");

                    b.HasIndex("Sig2DId");

                    b.HasIndex("Sig3AId");

                    b.HasIndex("Sig3DId");

                    b.HasIndex("Sig4AId");

                    b.HasIndex("Sig4DId");

                    b.HasIndex("StationId");

                    b.HasIndex("TrackAId");

                    b.HasIndex("TrackDId");

                    b.HasIndex("TrainId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("ServerData.Database.RowDataAcception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Accepted")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Changed")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Data")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("RowDataAcceptions");
                });

            modelBuilder.Entity("ServerData.Database.RowDataDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Changed")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Data")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.ToTable("RowDataDates");
                });

            modelBuilder.Entity("ServerData.Database.RowDataDelay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Minutes")
                        .HasColumnType("smallint");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<int?>("RowId1")
                        .HasColumnType("int");

                    b.Property<int?>("TrainNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("RowId1");

                    b.ToTable("RowDataDelays");
                });

            modelBuilder.Entity("ServerData.Database.RowDataSignaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Changed")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SignallerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Time")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SignallerId");

                    b.ToTable("RowDataSignallers");
                });

            modelBuilder.Entity("ServerData.Database.RowDataString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Changed")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RowDataStrings");
                });

            modelBuilder.Entity("ServerData.Database.RowDataTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Changed")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("Occupied")
                        .HasColumnType("bit");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RowDataTracks");
                });

            modelBuilder.Entity("ServerData.Database.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ServerData.Database.Signaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Signallers");
                });

            modelBuilder.Entity("ServerData.Database.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<byte>("Color")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<float>("TimePenalty")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PrimaryId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryId")
                        .HasColumnType("int");

                    b.Property<float>("TravelTime")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryId")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.HasIndex("SecondaryId")
                        .IsUnique();

                    b.ToTable("StationConnections");
                });

            modelBuilder.Entity("ServerData.Database.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Arrival")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Departure")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("FromId")
                        .HasColumnType("int");

                    b.Property<int?>("StationTrackId")
                        .HasColumnType("int");

                    b.Property<int?>("ToId")
                        .HasColumnType("int");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<byte>("TrainType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FromId")
                        .IsUnique()
                        .HasFilter("[FromId] IS NOT NULL");

                    b.HasIndex("StationTrackId")
                        .IsUnique()
                        .HasFilter("[StationTrackId] IS NOT NULL");

                    b.HasIndex("ToId")
                        .IsUnique()
                        .HasFilter("[ToId] IS NOT NULL");

                    b.HasIndex("TrackId");

                    b.HasIndex("TrainId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("ServerData.Database.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("ServerData.Database.TimetableStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<short?>("Arrival")
                        .HasColumnType("smallint");

                    b.Property<short?>("Departure")
                        .HasColumnType("smallint");

                    b.Property<int?>("FromId")
                        .HasColumnType("int");

                    b.Property<int?>("StationTrackId")
                        .HasColumnType("int");

                    b.Property<int?>("ToId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<byte>("TrainType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("StationTrackId");

                    b.HasIndex("ToId");

                    b.HasIndex("TrainId");

                    b.ToTable("TimetableStops");
                });

            modelBuilder.Entity("ServerData.Database.TimetableTrain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TimetableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("TimetableId");

                    b.ToTable("TimetableTrains");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("Platform")
                        .HasColumnType("bit");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("RouteId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("ServerData.Database.TrainEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Expired")
                        .HasColumnType("bit");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainEvents");
                });

            modelBuilder.Entity("ServerData.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("TokenIssued")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SignallerStation", b =>
                {
                    b.Property<int>("SignallersId")
                        .HasColumnType("int");

                    b.Property<int>("StationsId")
                        .HasColumnType("int");

                    b.HasKey("SignallersId", "StationsId");

                    b.HasIndex("StationsId");

                    b.ToTable("SignallerStation");
                });

            modelBuilder.Entity("RouteUser", b =>
                {
                    b.HasOne("ServerData.Database.Route", null)
                        .WithMany()
                        .HasForeignKey("RoutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Clients")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ServerData.Database.RouteTrack", b =>
                {
                    b.HasOne("ServerData.Database.StationConnection", "Connection")
                        .WithMany("RouteTracks")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("ServerData.Database.Row", b =>
                {
                    b.HasOne("ServerData.Database.RowDataDate", "APMD")
                        .WithMany()
                        .HasForeignKey("APMDId");

                    b.HasOne("ServerData.Database.RowDataDate", "AcceptedA")
                        .WithMany()
                        .HasForeignKey("AcceptedAId");

                    b.HasOne("ServerData.Database.RowDataDate", "AcceptedD")
                        .WithMany()
                        .HasForeignKey("AcceptedDId");

                    b.HasOne("ServerData.Database.RowDataDate", "ActualDepA")
                        .WithMany()
                        .HasForeignKey("ActualDepAId");

                    b.HasOne("ServerData.Database.RowDataDate", "ActualDepD")
                        .WithMany()
                        .HasForeignKey("ActualDepDId");

                    b.HasOne("ServerData.Database.RowDataDate", "AnnouncedA")
                        .WithMany()
                        .HasForeignKey("AnnouncedAId");

                    b.HasOne("ServerData.Database.RowDataAcception", "AnnouncedD")
                        .WithMany()
                        .HasForeignKey("AnnouncedDId");

                    b.HasOne("ServerData.Database.RowDataDate", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalId");

                    b.HasOne("ServerData.Database.RowDataString", "CommentA")
                        .WithMany()
                        .HasForeignKey("CommentAId");

                    b.HasOne("ServerData.Database.RowDataString", "CommentD")
                        .WithMany()
                        .HasForeignKey("CommentDId");

                    b.HasOne("ServerData.Database.RowDataDate", "DPMD")
                        .WithMany()
                        .HasForeignKey("DPMDId");

                    b.HasOne("ServerData.Database.RowDataDate", "DepartedA")
                        .WithMany()
                        .HasForeignKey("DepartedAId");

                    b.HasOne("ServerData.Database.RowDataDate", "DepartedD")
                        .WithMany()
                        .HasForeignKey("DepartedDId");

                    b.HasOne("ServerData.Database.RowDataDate", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureId");

                    b.HasOne("ServerData.Database.RowDataString", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("ServerData.Database.RowDataString", "NoteA")
                        .WithMany()
                        .HasForeignKey("NoteAId");

                    b.HasOne("ServerData.Database.RowDataString", "NoteD")
                        .WithMany()
                        .HasForeignKey("NoteDId");

                    b.HasOne("ServerData.Database.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig1A")
                        .WithMany()
                        .HasForeignKey("Sig1AId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig1D")
                        .WithMany()
                        .HasForeignKey("Sig1DId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig2A")
                        .WithMany()
                        .HasForeignKey("Sig2AId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig2D")
                        .WithMany()
                        .HasForeignKey("Sig2DId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig3A")
                        .WithMany()
                        .HasForeignKey("Sig3AId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig3D")
                        .WithMany()
                        .HasForeignKey("Sig3DId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig4A")
                        .WithMany()
                        .HasForeignKey("Sig4AId");

                    b.HasOne("ServerData.Database.RowDataSignaller", "Sig4D")
                        .WithMany()
                        .HasForeignKey("Sig4DId");

                    b.HasOne("ServerData.Database.Station", "Station")
                        .WithMany("Archive")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.RowDataTrack", "TrackA")
                        .WithMany()
                        .HasForeignKey("TrackAId");

                    b.HasOne("ServerData.Database.RowDataTrack", "TrackD")
                        .WithMany()
                        .HasForeignKey("TrackDId");

                    b.HasOne("ServerData.Database.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId");

                    b.Navigation("APMD");

                    b.Navigation("AcceptedA");

                    b.Navigation("AcceptedD");

                    b.Navigation("ActualDepA");

                    b.Navigation("ActualDepD");

                    b.Navigation("AnnouncedA");

                    b.Navigation("AnnouncedD");

                    b.Navigation("Arrival");

                    b.Navigation("CommentA");

                    b.Navigation("CommentD");

                    b.Navigation("DPMD");

                    b.Navigation("DepartedA");

                    b.Navigation("DepartedD");

                    b.Navigation("Departure");

                    b.Navigation("Message");

                    b.Navigation("NoteA");

                    b.Navigation("NoteD");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("Sig1A");

                    b.Navigation("Sig1D");

                    b.Navigation("Sig2A");

                    b.Navigation("Sig2D");

                    b.Navigation("Sig3A");

                    b.Navigation("Sig3D");

                    b.Navigation("Sig4A");

                    b.Navigation("Sig4D");

                    b.Navigation("Station");

                    b.Navigation("TrackA");

                    b.Navigation("TrackD");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("ServerData.Database.RowDataDelay", b =>
                {
                    b.HasOne("ServerData.Database.Row", null)
                        .WithMany("DelaysA")
                        .HasForeignKey("RowId");

                    b.HasOne("ServerData.Database.Row", null)
                        .WithMany("DelaysD")
                        .HasForeignKey("RowId1");
                });

            modelBuilder.Entity("ServerData.Database.RowDataSignaller", b =>
                {
                    b.HasOne("ServerData.Database.Signaller", "Signaller")
                        .WithMany()
                        .HasForeignKey("SignallerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signaller");
                });

            modelBuilder.Entity("ServerData.Database.Shift", b =>
                {
                    b.HasOne("ServerData.Database.Client", "Client")
                        .WithMany("Shifts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServerData.Database.Station", b =>
                {
                    b.HasOne("ServerData.Database.Client", "Client")
                        .WithMany("Stations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Primary")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.StationConnection", "PrimaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Connections")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Station", "Secondary")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.StationConnection", "SecondaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Primary");

                    b.Navigation("Route");

                    b.Navigation("Secondary");
                });

            modelBuilder.Entity("ServerData.Database.Stop", b =>
                {
                    b.HasOne("ServerData.Database.RouteTrack", "From")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "FromId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServerData.Database.Track", "Track")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "StationTrackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServerData.Database.RouteTrack", "To")
                        .WithOne()
                        .HasForeignKey("ServerData.Database.Stop", "ToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ServerData.Database.Track", null)
                        .WithMany("TrainStops")
                        .HasForeignKey("TrackId");

                    b.HasOne("ServerData.Database.Train", "Train")
                        .WithMany("Stops")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("Track");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("ServerData.Database.Timetable", b =>
                {
                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Timetables")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ServerData.Database.TimetableStop", b =>
                {
                    b.HasOne("ServerData.Database.RouteTrack", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("ServerData.Database.Track", "Track")
                        .WithMany()
                        .HasForeignKey("StationTrackId");

                    b.HasOne("ServerData.Database.RouteTrack", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.HasOne("ServerData.Database.TimetableTrain", "Train")
                        .WithMany("Stops")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");

                    b.Navigation("Track");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("ServerData.Database.TimetableTrain", b =>
                {
                    b.HasOne("ServerData.Database.Timetable", "Timetable")
                        .WithMany("Trains")
                        .HasForeignKey("TimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Station")
                        .WithMany("Tracks")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.HasOne("ServerData.Database.Route", "Route")
                        .WithMany("Trains")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("ServerData.Database.TrainEvent", b =>
                {
                    b.HasOne("ServerData.Database.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Train", null)
                        .WithMany("Events")
                        .HasForeignKey("TrainId");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SignallerStation", b =>
                {
                    b.HasOne("ServerData.Database.Signaller", null)
                        .WithMany()
                        .HasForeignKey("SignallersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerData.Database.Station", null)
                        .WithMany()
                        .HasForeignKey("StationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServerData.Database.Client", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("ServerData.Database.Route", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Connections");

                    b.Navigation("Timetables");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("ServerData.Database.Row", b =>
                {
                    b.Navigation("DelaysA");

                    b.Navigation("DelaysD");
                });

            modelBuilder.Entity("ServerData.Database.Station", b =>
                {
                    b.Navigation("Archive");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ServerData.Database.StationConnection", b =>
                {
                    b.Navigation("RouteTracks");
                });

            modelBuilder.Entity("ServerData.Database.Timetable", b =>
                {
                    b.Navigation("Trains");
                });

            modelBuilder.Entity("ServerData.Database.TimetableTrain", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("ServerData.Database.Track", b =>
                {
                    b.Navigation("TrainStops");
                });

            modelBuilder.Entity("ServerData.Database.Train", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("ServerData.Database.User", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
